---
- name: Testing Connectivity to DNA Center
  hosts: dnac_servers
  vars_files:
    - credentials.yml
  gather_facts: no
  tasks:
    - name: Getting Platform Release Summary
      cisco.dnac.platform_release_summary_info:
        dnac_host: "{{dnac_host}}"
        dnac_username: "{{dnac_username}}"
        dnac_password: "{{dnac_password}}"
        dnac_verify: "{{dnac_verify}}"
        dnac_port: "{{dnac_port}}"
        dnac_version: "{{dnac_version}}"
        dnac_debug: "{{dnac_debug}}"
      register: result
    
    - name: Printing Results
      ansible.builtin.debug:
        var: result